{"name": "test_0", "status": "failed", "statusDetails": {"message": "AssertionError: assert 5050 == 5051", "trace": "def      test_0():\n        n=0\n        for  i  in  range(1,101):\n            n+=i\n            # 预期结果是5050\n            # 实际结果是n\n            # 断言：那拿实际结果与预期结果进行对比的过程\n>       assert  n==5051\nE       assert 5050 == 5051\n\ntest_1.py:27: AssertionError"}, "start": 1565577336578, "stop": 1565577336579, "uuid": "5e9d800e-23df-4b91-92d0-6e488f370e2f", "historyId": "debb69768f2f715cfcfa904ea07c89c1", "fullName": "test_1#test_0", "labels": [{"name": "parentSuite"}, {"name": "suite", "value": "test_1"}, {"name": "subSuite"}, {"name": "host", "value": "杨彪"}, {"name": "thread", "value": "77820-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_1"}]}